### Health
GET {{baseUrl}}

### Register
POST {{baseUrl}}auth/register
Content-Type: application/json

{
  "username": "teammannow",
  "password": "password123",
  "role": "player"
}

### Login
POST {{baseUrl}}auth/login
Content-Type: application/json

{
  "username": "teammannow",
  "password": "password123"
}